# Header
menu:
  Home: /
  Archives: /archives
  Cocos: /Cocos
  WordPress: /WordPress
  About: /about
rss: /atom.xml

# Content
excerpt_link: 继续阅读
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
# - tag
- tagcloud
- archive
- recent_posts
- weibo
- blogroll

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# Scroll to top
go_top: true

# baidu 统计
baidu_tongji: true
